version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./node.Dockerfile
    volumes:
      - images:/app/server/animalsPhotos/
  app:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    ports:
      - '3000:80'
    volumes:
      - images:/usr/share/nginx/animalsPhotos/
volumes:
  images:
